name: SilkableSpawners
main: dev.foolen.silkablespawners.SilkableSpawners
version: 1.0
author: Tjeu Foolen
api-version: 1.13

permissions:
    silkablespawners.*:
        description: Gives access to all SilkableSpawners commands
        children:
            silkablespawners.break: true
            silkablespawners.place: true
    silkablespawners.break:
        description: Allows you to mine a spawner with a diamond silktouch pickaxe
        default: op
    silkablespawners.place:
        description: Allows you to place a mined spawner
        default: op